let pokemon = [{
    id: 1,
    name: "Bulbasaur",
    type: "Grass",
    image: 'Bulbasaur.png',
    gotcha: false,
  },
  {
    id: 2,
    name: "Ivysaur",
    type: "Grass",
    image: "Ivysaur.png",
    gotcha: false,
  },
  {
    id: 3,
    name: "Venusaur",
    type: "Grass",
    image: "Venusaur.png",
    gotcha: false,
  },
  {
    id: 4,
    name: "Charmander",
    type: "Fire",
    image: 'Charmander.png',
    gotcha: false,
  },
  {
    id: 5,
    name: "Charmeleon",
    type: "Fire",
    image: 'Charmeleon.png',
    gotcha: false,
  },
  {
    id: 6,
    name: "Charizard",
    type: "Fire",
    image: 'Charizard.png',
    gotcha: false,
  },
  {
    id: 7,
    name: "Squirtle",
    type: "Water",
    image: 'Squirtle.png',
    gotcha: false,
  },
  {
    id: 8,
    name: "Wartortle",
    type: "Water",
    image: 'Wartortle.png',
    gotcha: false,
  },
  {
    id: 9,
    name: "Blastoise",
    type: "Water",
    image: 'Blastoise.png',
    gotcha: false,
  },
  {
    id: 10,
    name: "Caterpie",
    type: "Bug",
    image: 'Caterpie.png',
    gotcha: false,
  },
  {
    id: 11,
    name: "Metapod",
    type: "Bug",
    image: "Metapod.png",
    gotcha: false,
  },
  {
    id: 12,
    name: "Butterfree",
    type: "Bug",
    image: "Butterfree.png",
    gotcha: false,
  },
  {
    id: 13,
    name: "Weedle",
    type: "Bug",
    image: "Weedle.png",
    gotcha: false,
  },
  {
    id: 14,
    name: "Kakuna",
    type: "Bug",
    image: "Kakuna.png",
    gotcha: false,
  },
  {
    id: 15,
    name: "Beedrill",
    type: "Bug",
    image: "Beedrill.png",
    gotcha: false,
  },
  {
    id: 16,
    name: "Pidgey",
    type: "Flying",
    image: "Pidgey.png",
    gotcha: false,
  },
  {
    id: 17,
    name: "Pidgeotto",
    type: "Flying",
    image: "Pidgeotto.png",
    gotcha: false,
  },
  {
    id: 18,
    name: "Pidgeot",
    type: "Flying",
    image: "Pidgeot.png",
    gotcha: false,
  },
  {
    id: 19,
    name: "Rattata",
    type: "Normal",
    image: "Rattata.png",
    gotcha: false,
  },
  {
    id: 20,
    name: "Raticate",
    type: "Normal",
    image: "Raticate.png",
    gotcha: false,
  },
  {
    id: 21,
    name: "Spearow",
    type: "Flying",
    image: "Spearow.png",
    gotcha: false,
  },
  {
    id: 22,
    name: "Fearow",
    type: "Flying",
    image: "Fearow.png",
    gotcha: false,
  },
  {
    id: 23,
    name: "Ekans",
    type: "Poison",
    image: "Ekans.png",
    gotcha: false,
  },
  {
    id: 24,
    name: "Arbok",
    type: "Poison",
    image: "Arbok.png",
    gotcha: false,
  },
  {
    id: 25,
    name: "Pikachu",
    type: "Electric",
    image: "Pikachu.png",
    gotcha: false,
  },
  {
    id: 26,
    name: "Raichu",
    type: "Electric",
    image: "Raichu.png",
    gotcha: false,
  },
  {
    id: 27,
    name: "Sandshrew",
    type: "Ground",
    image: "Sandshrew.png",
    gotcha: false,

  },
  {
    id: 28,
    name: "Sandslash",
    type: "Ground",
    image: "Sandslash.png",
    gotcha: false,
  },
  {
    id: 29,
    name: "NidoranF",
    type: "Poison",
    image: "NidoranF.png",
    gotcha: false,
  },
  {
    id: 30,
    name: "Nidorina",
    type: "Poison",
    image: "Nidorina.png",
    gotcha: false,

  },
  {
    id: 31,
    name: "Nidoqueen",
    type: "Poison",
    image: "Nidoqueen.png",
    gotcha: false,
  },
  {
    id: 32,
    name: "NidoranM",
    type: "Poison",
    image: "NidoranM.png",
    gotcha: false,
  },
  {
    id: 33,
    name: "Nidorino",
    type: "Poison",
    image: "Nidorino.png",
    gotcha: false,
  },
  {
    id: 34,
    name: "Nidoking",
    type: "Poison",
    image: "Nidoking.png",
    gotcha: false,
  },
  {
    id: 35,
    name: "Clefairy",
    type: "Fairy",
    image: "Clefairy.png",
    gotcha: false,
  },
  {
    id: 36,
    name: "Clefable",
    type: "Fairy",
    image: "Clefable.png",
    gotcha: false,
  },
  {
    id: 37,
    name: "Vulpix",
    type: "Fire",
    image: "Vulpix.png",
    gotcha: false,
  },
  {
    id: 38,
    name: "Ninetales",
    type: "Fire",
    image: "Ninetales.png",
    gotcha: false,
  },
  {
    id: 39,
    name: "Jigglypuff",
    type: "Fairy",
    image: "Jigglypuff.png",
    gotcha: false,
  },
  {
    id: 40,
    name: "Wigglytuff",
    type: "Fairy",
    image: "Wigglytuff.png",
    gotcha: false,
  },
  {
    id: 41,
    name: "Zubat",
    type: "Poison",
    image: 'Zubat.png',
    gotcha: false,
  },
  {
    id: 42,
    name: "Golbat",
    type: "Poison",
    image: 'Golbat.png',
    gotcha: false,
  },
  {
    id: 43,
    name: "Oddish",
    type: "Grass",
    image: 'Oddish.png',
    gotcha: false,
  },
  {
    id: 44,
    name: "Gloom",
    type: "Grass",
    image: 'Gloom.png',
    gotcha: false,
  },
  {
    id: 45,
    name: "Vileplume",
    type: "Grass",
    image: 'Vileplume.png',
    gotcha: false,
  },
  {
    id: 46,
    name: "Paras",
    type: "Bug",
    image: 'Paras.png',
    gotcha: false,
  },
  {
    id: 47,
    name: "Parasect",
    type: "Bug",
    image: 'Parasect.png',
    gotcha: false,
  },
  {
    id: 48,
    name: "Venonat",
    type: "Bug",
    image: 'Venonat.png',
    gotcha: false,
  },
  {
    id: 49,
    name: "Venomoth",
    type: "Bug",
    image: 'Venomoth.png',
    gotcha: false,
  },
  {
    id: 50,
    name: "Diglett",
    type: "Ground",
    image: 'Diglett.png',
    gotcha: false,
  },
  {
    id: 51,
    name: "Dugtrio",
    type: "Ground",
    image: 'Dugtrio.png',
    gotcha: false,
  },
  {
    id: 52,
    name: "Dugtrio",
    type: "Normal",
    image: 'Meowth.png',
    gotcha: false,
  },
  {
    id: 53,
    name: "Persian",
    type: "Normal",
    image: 'Persian.png',
    gotcha: false,
  },
  {
    id: 54,
    name: "Psyduck",
    type: "Water",
    image: 'Psyduck.png',
    gotcha: false,
  },
  {
    id: 55,
    name: "Golduck",
    type: "Water",
    image: 'Golduck.png',
    gotcha: false,
  },
  {
    id: 56,
    name: "Mankey",
    type: "Fighting",
    image: 'Mankey.png',
    gotcha: false,
  },
  {
    id: 57,
    name: "Primeape",
    type: "Fighting",
    image: 'Primeape.png',
    gotcha: false,
  },
  {
    id: 58,
    name: "Growlithe",
    type: "Fire",
    image: 'Growlithe.png',
    gotcha: false,
  },
  {
    id: 59,
    name: "Arcanine",
    type: "Fire",
    image: 'Arcanine.png',
    gotcha: false,
  },
  {
    id: 60,
    name: "Poliwag",
    type: "Water",
    image: 'Poliwag.png',
    gotcha: false,
  },
  {
    id: 61,
    name: "Poliwhirl",
    type: "Water",
    image: 'Poliwhirl.png',
    gotcha: false,
  },
  {
    id: 62,
    name: "Poliwrath",
    type: "Water",
    image: 'Poliwrath.png',
    gotcha: false,
  },
  {
    id: 63,
    name: "Abra",
    type: "Psychic",
    image: 'Abra.png',
    gotcha: false,
  },
  {
    id: 64,
    name: "Kadabra",
    type: "Psychic",
    image: 'Kadabra.png',
    gotcha: false,
  },
  {
    id: 65,
    name: "Alakazam",
    type: "Psychic",
    image: 'Alakazam.png',
    gotcha: false,
  },
  {
    id: 66,
    name: "Machop",
    type: "Fighting",
    image: 'Machop.png',
    gotcha: false,
  },
  {
    id: 67,
    name: "Machoke",
    type: "Fighting",
    image: 'Machoke.png',
    gotcha: false,
  },
  {
    id: 68,
    name: "Machamp",
    type: "Fighting",
    image: 'Machamp.png',
    gotcha: false,
  },
  {
    id: 69,
    name: "Bellsprout",
    type: "Grass",
    image: 'Bellsprout.png',
    gotcha: false,
  },
  {
    id: 70,
    name: "Weepinbell",
    type: "Grass",
    image: 'Weepinbell.png',
    gotcha: false,
  },
  {
    id: 71,
    name: "Victreebel",
    type: "Grass",
    image: 'Victreebel.png',
    gotcha: false,
  },
  {
    id: 72,
    name: "Tentacool",
    type: "Water",
    image: 'Tentacool.png',
    gotcha: false,
  },
  {
    id: 73,
    name: "Tentacruel",
    type: "Water",
    image: 'Tentacruel.png',
    gotcha: false,
  },
  {
    id: 74,
    name: "Geodude",
    type: "Rock",
    image: 'Geodude.png',
    gotcha: false,
  },
  {
    id: 75,
    name: "Graveler",
    type: "Rock",
    image: 'Graveler.png',
    gotcha: false,
  },
  {
    id: 76,
    name: "Golem",
    type: "Rock",
    image: 'Golem.png',
    gotcha: false,
  },
  {
    id: 77,
    name: "Ponyta",
    type: "Fire",
    image: 'Ponyta.png',
    gotcha: false,
  },
  {
    id: 78,
    name: "Rapidash",
    type: "Fire",
    image: 'Rapidash.png',
    gotcha: false,
  },
  {
    id: 79,
    name: "Slowpoke",
    type: "Water",
    image: 'Slowpoke.png',
    gotcha: false,
  },
  {
    id: 80,
    name: "Slowbro",
    type: "Water",
    image: 'Slowbro.png',
    gotcha: false,
  },
  {
    id: 81,
    name: "Magnemite",
    type: "Electric",
    image: 'Magnemite.png',
    gotcha: false,
  },
  {
    id: 82,
    name: "Magneton",
    type: "Electric",
    image: 'Magneton.png',
    gotcha: false,
  },
  {
    id: 83,
    name: "Farfetchd",
    type: "Normal",
    image: 'Farfetchd.png',
    gotcha: false,
  },
  {
    id: 84,
    name: "Doduo",
    type: "Flying",
    image: 'Doduo.png',
    gotcha: false,
  },
  {
    id: 85,
    name: "Dodrio",
    type: "Flying",
    image: 'Dodrio.png',
    gotcha: false,
  },
  {
    id: 86,
    name: "Seel",
    type: "Water",
    image: 'Seel.png',
    gotcha: false,
  },
  {
    id: 87,
    name: "Dewgong",
    type: "Water",
    image: 'Dewgong.png',
    gotcha: false,
  },
  {
    id: 88,
    name: "Grimer",
    type: "Poison",
    image: 'Grimer.png',
    gotcha: false,
  },
  {
    id: 89,
    name: "Muk",
    type: "Poison",
    image: 'Muk.png',
    gotcha: false,
  },
  {
    id: 90,
    name: "Shellder",
    type: "Water",
    image: 'Shellder.png',
    gotcha: false,
  },
  {
    id: 91,
    name: "Cloyster",
    type: "Water",
    image: 'Cloyster.png',
    gotcha: false,
  },
  {
    id: 92,
    name: "Gastly",
    type: "Ghost",
    image: 'Gastly.png',
    gotcha: false,
  },
  {
    id: 93,
    name: "Haunter",
    type: "Ghost",
    image: 'Haunter.png',
    gotcha: false,
  },
  {
    id: 94,
    name: "Gengar",
    type: "Ghost",
    image: 'Gengar.png',
    gotcha: false,
  },
  {
    id: 95,
    name: "Onix",
    type: "Rock",
    image: 'Onix.png',
    gotcha: false,
  },
  {
    id: 96,
    name: "Drowzee",
    type: "Psychic",
    image: 'Drowzee.png',
    gotcha: false,
  },
  {
    id: 97,
    name: "Hypno",
    type: "Psychic",
    image: 'Hypno.png',
    gotcha: false,
  },
  {
    id: 98,
    name: "Krabby",
    type: "Water",
    image: 'Krabby.png',
    gotcha: false,
  },
  {
    id: 99,
    name: "Kingler",
    type: "Water",
    image: 'Kingler.png',
    gotcha: false,
  },
  {
    id: 100,
    name: "Voltorb",
    type: "Electric",
    image: 'Voltorb.png',
    gotcha: false,
  },
  {
    id: 101,
    name: "Electrode",
    type: "Electric",
    image: 'Electrode.png',
    gotcha: false,
  },
  {
    id: 102,
    name: "Exeggcute",
    type: "Grass",
    image: 'Exeggcute.png',
    gotcha: false,
  },
  {
    id: 103,
    name: "Exeggutor",
    type: "Grass",
    image: 'Exeggutor.png',
    gotcha: false,
  },
  {
    id: 104,
    name: "Cubone",
    type: "Ground",
    image: 'Cubone.png',
    gotcha: false,
  },
  {
    id: 105,
    name: "Marowak",
    type: "Ground",
    image: 'Marowak.png',
    gotcha: false,
  },
  {
    id: 106,
    name: "Hitmonlee",
    type: "Fighting",
    image: 'Hitmonlee.png',
    gotcha: false,
  },
  {
    id: 107,
    name: "Hitmonchan",
    type: "Fighting",
    image: 'Hitmonchan.png',
    gotcha: false,
  },
  {
    id: 108,
    name: "Lickitung",
    type: "Normal",
    image: 'Lickitung.png',
    gotcha: false,
  },
  {
    id: 109,
    name: "Koffing",
    type: "Poison",
    image: 'Koffing.png',
    gotcha: false,
  },
  {
    id: 110,
    name: "Weezing",
    type: "Poison",
    image: 'Weezing.png',
    gotcha: false,
  },
  {
    id: 111,
    name: "Rhyhorn",
    type: "Ground",
    image: 'Rhyhorn.png',
    gotcha: false,
  },
  {
    id: 112,
    name: "Rhydon",
    type: "Ground",
    image: 'Rhydon.png',
    gotcha: false,
  },
  {
    id: 113,
    name: "Chansey",
    type: "Normal",
    image: 'Chansey.png',
    gotcha: false,
  },
  {
    id: 114,
    name: "Tangela",
    type: "Grass",
    image: 'Tangela.png',
    gotcha: false,
  },
  {
    id: 115,
    name: "Kangaskhan",
    type: "Normal",
    image: 'Kangaskhan.png',
    gotcha: false,
  },
  {
    id: 116,
    name: "Horsea",
    type: "Water",
    image: 'Horsea.png',
    gotcha: false,
  },
  {
    id: 117,
    name: "Seadra",
    type: "Water",
    image: 'Seadra.png',
    gotcha: false,
  },
  {
    id: 118,
    name: "Goldeen",
    type: "Water",
    image: 'Goldeen.png',
    gotcha: false,
  },
  {
    id: 119,
    name: "Seaking",
    type: "Water",
    image: 'Seaking.png',
    gotcha: false,
  },
  {
    id: 120,
    name: "Staryu",
    type: "Water",
    image: 'Staryu.png',
    gotcha: false,
  },
  {
    id: 121,
    name: "Starmie",
    type: "Water",
    image: 'Starmie.png',
    gotcha: false,
  },
  {
    id: 122,
    name: "Mr_Mime",
    type: "Psychic",
    image: 'Mr_Mime.png',
    gotcha: false,
  },
  {
    id: 123,
    name: "Scyther",
    type: "Bug",
    image: 'Scyther.png',
    gotcha: false,
  },
  {
    id: 124,
    name: "Jynx",
    type: "Ice",
    image: 'Jynx.png',
    gotcha: false,
  },
  {
    id: 125,
    name: "Electabuzz",
    type: "Electric",
    image: 'Electabuzz.png',
    gotcha: false,
  },
  {
    id: 126,
    name: "Magmar",
    type: "Fire",
    image: 'Magmar.png',
    gotcha: false,
  },
  {
    id: 127,
    name: "Pinsir",
    type: "Bug",
    image: 'Pinsir.png',
    gotcha: false,
  },
  {
    id: 128,
    name: "Tauros",
    type: "Normal",
    image: 'Tauros.png',
    gotcha: false,
  },
  {
    id: 129,
    name: "Magikarp",
    type: "Water",
    image: 'Magikarp.png',
    gotcha: false,
  },
  {
    id: 130,
    name: "Gyarados",
    type: "Water",
    image: 'Gyarados.png',
    gotcha: false,
  },
  {
    id: 131,
    name: "Lapras",
    type: "Water",
    image: 'Lapras.png',
    gotcha: false,
  },
  {
    id: 132,
    name: "Ditto",
    type: "Normal",
    image: 'Ditto.png',
    gotcha: false,
  },
  {
    id: 133,
    name: "Eevee",
    type: "Normal",
    image: 'Eevee.png',
    gotcha: false,
  },
  {
    id: 134,
    name: "Vaporeon",
    type: "Water",
    image: 'Vaporeon.png',
    gotcha: false,
  },
  {
    id: 135,
    name: "Jolteon",
    type: "Electric",
    image: 'Jolteon.png',
    gotcha: false,
  },
  {
    id: 136,
    name: "Flareon",
    type: "Fire",
    image: 'Flareon.png',
    gotcha: false,
  },
  {
    id: 137,
    name: "Porygon",
    type: "Normal",
    image: 'Porygon.png',
    gotcha: false,
  },
  {
    id: 138,
    name: "Omanyte",
    type: "Rock",
    image: 'Omanyte.png',
    gotcha: false,
  },
  {
    id: 139,
    name: "Omastar",
    type: "Rock",
    image: 'Omastar.png',
    gotcha: false,
  },
  {
    id: 140,
    name: "Kabuto",
    type: "Rock",
    image: 'Kabuto.png',
    gotcha: false,
  },
  {
    id: 141,
    name: "Kabutops",
    type: "Rock",
    image: 'Kabutops.png',
    gotcha: false,
  },
  {
    id: 142,
    name: "Aerodactyl",
    type: "Rock",
    image: 'Aerodactyl.png',
    gotcha: false,
  },
  {
    id: 143,
    name: "Snorlax",
    type: "Normal",
    image: 'Snorlax.png',
    gotcha: false,
  },
  {
    id: 144,
    name: "Articuno",
    type: "Ice",
    image: 'Articuno.png',
    gotcha: false,
  },
  {
    id: 145,
    name: "Zapdos",
    type: "Electric",
    image: 'Zapdos.png',
    gotcha: false,
  },
  {
    id: 146,
    name: "Moltres",
    type: "Fire",
    image: 'Moltres.png',
    gotcha: false,
  },
  {
    id: 147,
    name: "Dratini",
    type: "Dragon",
    image: 'Dratini.png',
    gotcha: false,
  },
  {
    id: 148,
    name: "Dragonair",
    type: "Dragon",
    image: 'Dragonair.png',
    gotcha: false,
  },
  {
    id: 149,
    name: "Dragonite",
    type: "Dragon",
    image: 'Dragonite.png',
    gotcha: false,
  },
  {
    id: 150,
    name: "Mewtwo",
    type: "Psychic",
    image: 'Mewtwo.png',
    gotcha: false,
  },
  {
    id: 151,
    name: "Mew",
    type: "Psychic",
    image: 'Mew.png',
    gotcha: false,
  },


]

export default pokemon;
